name: Build Tools

on:
  push:
    branches:
      - main
  schedule:
    # Build weekly on Fridays at midnight UTC
    - cron: '0 0 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        make build